### ISSUE TITLE
go-faiss创建索引只支持欧式距离,不支持内积距离么

### ISSUE THREAD

**Issue by computerAItest** [41tair/go-faiss#3]
go-faiss创建索引只支持欧式距离,不支持内积距离么

index := &faiss.Index{
		Dimension:   dimension,
		Description: "IDMap,Flat",
		MetricType:  faiss.L2{}, 
	}

这个L2可以替换成内积距离么,但是没找到

**Comment by 41tair** [comment]
Only support L2.
the project just create for fun.I can't promise it will be updated.
