### ISSUE TITLE
Go run example failed with error

### ISSUE THREAD

**Issue by XuChen-Repair** [41tair/go-faiss#4]
Hi, I followed the set-up wiki and still met below error when I run example.go

github.com/41tair/go-faiss/faiss
/usr/bin/ld: cannot find -lfaiss_c
/usr/bin/ld: cannot find -lfaiss_c
collect2: error: ld returned 1 exit status

**Comment by 41tair** [comment]
You can try add LDDPATH or modify ld.conf.d/*.conf, make sure faiss_c.h can be found

**Comment by XuChen-Repair** [comment]
Issue solved by copying the files to /usr/local/lib and set library path

**Comment by orihabAnyvision** [comment]
which files did you need to copy? I have the same issue and i have:
```
$ ls /usr/local/lib/ -l
total 21160
-rw-r--r-- 1 root root  21653074 Jun 15 11:00 libfaiss.a
drwxr-xr-x 4 root root      4096 Sep 16  2019 node_modules
```
already in there. any ideas?
